// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAwBNUOMNHLKXG7S1795uuP3LFXbcOOV0',
    appId: '1:35623226061:web:ce0d6a88e4e3a87477f784',
    messagingSenderId: '35623226061',
    projectId: 'shopping-app-b07eb',
    authDomain: 'shopping-app-b07eb.firebaseapp.com',
    storageBucket: 'shopping-app-b07eb.firebasestorage.app',
    measurementId: 'G-7194CFKS57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVp_FCMdIknpAKoQ2EnNv9zo5-6DD_L6A',
    appId: '1:35623226061:android:a35b25fcd800e88277f784',
    messagingSenderId: '35623226061',
    projectId: 'shopping-app-b07eb',
    storageBucket: 'shopping-app-b07eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJoxJc_3NIqca68TzNYZxNbKr6YNaPXoI',
    appId: '1:35623226061:ios:c14e012b11b5fa4e77f784',
    messagingSenderId: '35623226061',
    projectId: 'shopping-app-b07eb',
    storageBucket: 'shopping-app-b07eb.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJoxJc_3NIqca68TzNYZxNbKr6YNaPXoI',
    appId: '1:35623226061:ios:c14e012b11b5fa4e77f784',
    messagingSenderId: '35623226061',
    projectId: 'shopping-app-b07eb',
    storageBucket: 'shopping-app-b07eb.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAwBNUOMNHLKXG7S1795uuP3LFXbcOOV0',
    appId: '1:35623226061:web:f6a0a116a712871777f784',
    messagingSenderId: '35623226061',
    projectId: 'shopping-app-b07eb',
    authDomain: 'shopping-app-b07eb.firebaseapp.com',
    storageBucket: 'shopping-app-b07eb.firebasestorage.app',
    measurementId: 'G-V7NNFK9P4J',
  );
}
